spring:
  application:
    name: c2b-inventory-service
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: ${HIKARI_MIN_IDLE}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE}
