DB_HOST: jdbc:mysql://localhost:3306/omsAdmin
DB_USER: rahul
DB_PASSWORD: rahul

SHOW_SQL: false
FORMAT_SQL: false

HIKARI_MIN_IDLE: 5
HIKARI_CONNECTION_TIMEOUT: 5000
HIKARI_MAX_POOL_SIZE: 10
HIBERNATE_HBM2DDL_AUTO: none