#system property
# hibernate.generate_statistics=true

#log more info for what is happening in Hibernate
logging.level:
  org:
    hibernate:
      stat: DEBUG # log statistics
      SQL: DEBUG # log all statements
      SQL_SLOW: info

#slow query log
spring:
  jpa:
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE # Caching
      hibernate:
        generate_statistics: true # generate statistics
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS=20: 20 # configure threshold for log slow queries



#    database-platform: "org.hibernate.dialect.H2Dialect"
#
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: "org.h2.Driver"
#    username: sa
#    password:

  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    hikari:
      minimum-idle: ${HIKARI_MIN_IDLE}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE}






